cmake_minimum_required(VERSION 3.2)

set(MATHUTILS_INCLUDE_PATHS ${MATHUTILS_INCLUDE_PATHS}
    /lib/include
    /lib/local/include)

if(INSTALL_EXTERNAL_PROJECTS_PREFIX)
  set(MATHUTILS_INCLUDE_PATHS ${MATHUTILS_INCLUDE_PATHS}
      ${INSTALL_EXTERNAL_PROJECTS_PREFIX}/include)
endif()

if(EXTERNAL_PROJECTS_PATHS)
  set(MATHUTILS_INCLUDE_PATHS ${MATHUTILS_INCLUDE_PATHS}
      ${EXTERNAL_PROJECTS_PATHS}/include)
endif()

find_path(MATHUTILS_INCLUDE_PATH
          NAMES mathutils
          PATHS ${MATHUTILS_INCLUDE_PATHS})

if(NOT MATHUTILS_INCLUDE_PATH)
  include(${CMAKE_CURRENT_LIST_DIR}/mathutils.cmake)
endif()
