cmake_minimum_required(VERSION 3.2)

# spp settings
include(ExternalProject)

set(SPP_PROJECT_NAME spp)
set(SPP_GIT_REPOSITORY https://github.com/rxnew/spp.git)
set(SPP_GIT_TAG develop)

set(EXTERNAL_PROJECTS_INCLUDE_PATHS
    ${MATHUTILS_INCLUDE_PATH}
    ${JSON11_INCLUDE_PATH})

set(EXTERNAL_PROJECTS_LIBRARIES
    ${JSON11_LIBRARY})

ExternalProject_Add(
  ${SPP_PROJECT_NAME}
  GIT_REPOSITORY ${SPP_GIT_REPOSITORY}
  GIT_TAG ${SPP_GIT_TAG}
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/projects/${SPP_PROJECT_NAME}
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${INSTALL_EXTERNAL_PROJECTS_PREFIX}
             -DEXTERNAL_PROJECTS_INCLUDE_PATHS=${EXTERNAL_PROJECTS_INCLUDE_PATHS}
             -DEXTERNAL_PROJECTS_LIBRARIES=${EXTERNAL_PROJECTS_LIBRARIES}
             -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
             -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  INSTALL_COMMAND ""
  LOG_DOWNLOAD on
  )

set(SPP_INCLUDE_PATH ${INSTALL_EXTERNAL_PROJECTS_PREFIX}/include)

if(BUILD_EXTERNAL_PROJECT_NAMES)
  add_dependencies(${SPP_PROJECT_NAME} ${BUILD_EXTERNAL_PROJECT_NAMES})
endif()

set(BUILD_EXTERNAL_PROJECT_NAMES ${BUILD_EXTERNAL_PROJECT_NAMES}
    ${SPP_PROJECT_NAME})
