cmake_minimum_required(VERSION 3.2)

# graph settings
include(ExternalProject)

set(GRAPH_PROJECT_NAME graph)
set(GRAPH_GIT_REPOSITORY https://github.com/rxnew/graph.git)
set(GRAPH_GIT_TAG v1.0.1)

ExternalProject_Add(
  ${GRAPH_PROJECT_NAME}
  GIT_REPOSITORY ${GRAPH_GIT_REPOSITORY}
  GIT_TAG ${GRAPH_GIT_TAG}
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/projects/${GRAPH_PROJECT_NAME}
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${INSTALL_EXTERNAL_PROJECTS_PREFIX}
  LOG_DOWNLOAD on
  )

set(GRAPH_INCLUDE_PATH ${INSTALL_EXTERNAL_PROJECTS_PREFIX}/include)

set(BUILD_EXTERNAL_PROJECT_NAMES ${BUILD_EXTERNAL_PROJECT_NAMES}
    ${GRAPH_PROJECT_NAME})
